layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: Angular
    web_url: https://angular.io/
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/angular/angular.png

  - name: React
    web_url: https://reactjs.org/
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/react/react.png

  - name: PWA
    image_url: https://raw.githubusercontent.com/github/explore/2a383f869b42519f223f6879a3ffc3ea7e0e596c/topics/pwa/pwa.png

  - name: NodeJS
    web_url: https://nodejs.org/
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/nodejs/nodejs.png

  - name: Serverless
    web_url: https://www.serverless.com/
    image_url: https://s3-us-west-2.amazonaws.com/assets.site.serverless.com/logos/serverless-square-icon-text.png

  - name: GraphQL
    web_url: https://graphql.github.io/
    image_url: https://raw.githubusercontent.com/github/explore/5e06fe2d36f72ea478fa4d30eb8a253aab676608/topics/graphql/graphql.png
